# Generated by Django 5.0.4 on 2026-03-16 20:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combination',
            name='description',
        ),
        migrations.RemoveField(
            model_name='combination',
            name='name',
        ),
        migrations.RemoveField(
            model_name='studentenrollment',
            name='combination',
        ),
        migrations.CreateModel(
            name='StudentCombinationAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateField(default=django.utils.timezone.now, help_text='Date when this combination was assigned')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this is the current active combination assignment')),
                ('remarks', models.TextField(blank=True, help_text='Any notes about this assignment (reason for change, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('combination', models.ForeignKey(help_text='The combination assigned to the student', on_delete=django.db.models.deletion.PROTECT, related_name='student_assignments', to='core.combination')),
                ('enrollment', models.ForeignKey(help_text='The enrollment this combination assignment belongs to', limit_choices_to={'class_level__educational_level__level_type': 'A_LEVEL'}, on_delete=django.db.models.deletion.CASCADE, related_name='combination_assignments', to='core.studentenrollment')),
                ('student', models.ForeignKey(help_text='The A-Level student assigned to this combination', on_delete=django.db.models.deletion.CASCADE, related_name='combination_assignments', to='core.student')),
            ],
            options={
                'verbose_name': 'Student Combination Assignment',
                'verbose_name_plural': 'Student Combination Assignments',
                'ordering': ['-assigned_date', 'student'],
                'indexes': [models.Index(fields=['student', '-assigned_date'], name='core_studen_student_2b3ba2_idx'), models.Index(fields=['combination', 'is_active'], name='core_studen_combina_5c37e2_idx'), models.Index(fields=['enrollment', 'is_active'], name='core_studen_enrollm_4f4cfd_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='studentcombinationassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('enrollment', 'is_active'), name='unique_active_combination_per_enrollment'),
        ),
    ]
