# Generated by Django 5.0.4 on 2026-03-18 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_combination_description_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='school',
            unique_together={('name', 'educational_level')},
        ),
    ]
