# Generated by Django 5.0.4 on 2026-03-18 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_school_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ['name', 'location'], 'verbose_name': 'School', 'verbose_name_plural': 'Schools'},
        ),
        migrations.AlterUniqueTogether(
            name='school',
            unique_together=set(),
        ),
    ]
