# Generated by Django 5.0.4 on 2026-03-25 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_school_options_alter_school_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='School code (e.g., RISS-PRIMARY)', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Full school name', max_length=200)),
                ('registration_number', models.CharField(help_text='Official registration number', max_length=50, unique=True)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('alternative_phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('motto', models.CharField(blank=True, max_length=200)),
                ('vision', models.TextField(blank=True)),
                ('mission', models.TextField(blank=True)),
                ('established_year', models.PositiveIntegerField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='school/logos/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact_person', models.ForeignKey(blank=True, help_text='Headmaster/Principal of this school', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_profiles_managed', to='core.staff')),
                ('educational_level', models.ForeignKey(blank=True, help_text='Educational level this school serves (leave blank for main record)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_profiles', to='core.educationallevel')),
            ],
            options={
                'verbose_name': 'School Profile',
                'verbose_name_plural': 'School Profiles',
                'ordering': ['code'],
                'unique_together': {('code', 'educational_level')},
            },
        ),
    ]
