# Generated by Django 5.0.4 on 2026-03-25 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_schoolprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolprofile',
            name='educational_level',
            field=models.ForeignKey(blank=True, help_text='Educational level this school serves (leave blank for main record)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_profiles', to='core.educationallevel'),
        ),
    ]
